In [1]:
import pandas as pd 

data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url,sep='\s+',header=None)
df_data.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [2]:
import numpy as np

df_data['weight_0'] = 1
df_data = df_data.drop("MEDV", axis=1)
df_matrix = df_data.values
weight_vector = np.random.random_sample((14, 1))
df_matrix.dot(weight_vector)

array([[605.72240474],
       [561.73353643],
       [551.85566687],
       [534.5291421 ],
       [539.67539199],
       [537.32954535],
       [624.76855686],
       [635.4503234 ],
       [636.21136318],
       [623.74779794],
       [632.84946477],
       [628.87083296],
       [619.96552889],
       [608.88155358],
       [598.02726421],
       [607.18446459],
       [595.09704314],
       [607.60087493],
       [512.38242376],
       [606.60914963],
       [605.98620507],
       [612.76192168],
       [621.63580649],
       [621.21776064],
       [617.20198168],
       [535.39351356],
       [599.95362986],
       [539.30039172],
       [608.67393391],
       [600.43085669],
       [592.48955342],
       [599.74849233],
       [482.06756289],
       [587.35428857],
       [491.33934634],
       [588.10270838],
       [571.64118364],
       [584.64684273],
       [581.57550663],
       [627.00322972],
       [624.40154667],
       [534.22821916],
       [533.50097648],
       [544

In [3]:
import numpy as np

test_array = np.array([1,4,5,8],float)
print(test_array)
print(type(test_array))
print(type(test_array[3]))

[1. 4. 5. 8.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [4]:
import numpy as np

test_array = np.array([1,4,5,8])
print(test_array)
print(type(test_array))
print(type(test_array[3]))

[1 4 5 8]
<class 'numpy.ndarray'>
<class 'numpy.int32'>


In [5]:
import numpy as np

test_list = [[1,4,5,8],[1,4,5]]
np.array(test_list, float)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [7]:
import numpy as np

# 2D의 넘파이 배열 생성
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# 배열의 strides 확인
print(arr.strides)

(12, 4)


In [8]:
test_array = np.array([1,4,5,"8"], float)
print(test_array)

[1. 4. 5. 8.]


In [9]:
print(type(test_array[3]))

<class 'numpy.float64'>


In [10]:
print(test_array.dtype)

float64


In [11]:
print(test_array.shape)

(4,)
